obj-y := board.o headsmp.o
obj-y += powergate.o clocktree-atm7059.o clocktree-owl.o sirq.o timer.o
obj-y += pinctrl-owl.o gpio.o
obj-y += hdmac.o serial.o
obj-y += wifibt.o emmc.o
obj-y += ethernet.o
obj-y += usb/
obj-y += video/
obj-y += labrador-pm.o atc2903c-pm.o 
#obj-y += sound/


