#snd-soc-atc2603c-objs := atc2603c-codec/atc2603c-audio-codec.o
snd-soc-dai-owl-objs  := dai-owl.o
snd-soc-pcm-owl-objs  := pcm-owl.o dmaengine-pcm-owl.o
snd-soc-link-owl-objs := link-owl.o

#obj-y += snd-soc-pcm-owl.o snd-soc-atc2603c.o snd-soc-dai-owl.o snd-soc-link-owl.o


obj-y += snd-soc-pcm-owl.o snd-soc-dai-owl.o snd-soc-link-owl.o

